"use client";
import { Document, Page, StyleSheet, Text, View, PDFDownloadLink } from "@react-pdf/renderer";
import { QRCodeSVG } from "qrcode.react";
import { amountInWords } from "@/lib/gst";

type Item = { description: string; hsnCode: string; quantity: number; unit: string; rate: number; gstRate: number };
type Props = { invoice: { number: string; customer: string; date: string; items: Item[]; subtotal?: number; cgst?: number; sgst?: number; igst?: number; totalTax?: number; grandTotal?: number }; business?: { businessName?: string | null; gstin?: string | null; address?: string | null; state?: string | null; bankName?: string | null; bankAccountNumber?: string | null; bankIfsc?: string | null; upiId?: string | null } };
const s = StyleSheet.create({ page: { padding: 32, fontSize: 9, color: "#17251d" }, header: { flexDirection: "row", justifyContent: "space-between", borderBottomWidth: 2, borderBottomColor: "#1f5d48", paddingBottom: 12 }, title: { fontSize: 19, color: "#1f5d48", fontWeight: "bold" }, section: { marginTop: 18 }, tableHead: { flexDirection: "row", backgroundColor: "#1f5d48", color: "white", padding: 7 }, row: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#dbe5df", padding: 7 }, desc: { width: "30%" }, col: { width: "14%" }, totals: { marginTop: 16, marginLeft: "55%" }, total: { flexDirection: "row", justifyContent: "space-between", marginBottom: 5 }, footer: { marginTop: 32, borderTopWidth: 1, borderTopColor: "#dbe5df", paddingTop: 12 } });
const money = (n: number) => `₹${n.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
function GSTInvoice({ invoice, business }: Props) { const subtotal = invoice.subtotal ?? invoice.items.reduce((n, i) => n + i.quantity * i.rate, 0); const tax = invoice.totalTax ?? invoice.items.reduce((n, i) => n + i.quantity * i.rate * i.gstRate / 100, 0); const total = invoice.grandTotal ?? subtotal + tax; return <Document><Page size="A4" style={s.page}><View style={s.header}><View><Text style={s.title}>{business?.businessName || "HisaabKaro Business"}</Text><Text>{business?.address || "India"}</Text><Text>GSTIN: {business?.gstin || "—"} | State: {business?.state || "—"}</Text></View><View><Text style={s.title}>TAX INVOICE</Text><Text>{invoice.number}</Text><Text>Date: {new Date(invoice.date).toLocaleDateString("en-IN")}</Text></View></View><View style={s.section}><Text>Bill to</Text><Text style={{ fontSize: 12, fontWeight: "bold" }}>{invoice.customer}</Text></View><View style={s.section}><View style={s.tableHead}><Text style={s.desc}>Description</Text><Text style={s.col}>HSN</Text><Text style={s.col}>Qty</Text><Text style={s.col}>Rate</Text><Text style={s.col}>GST</Text><Text style={s.col}>Amount</Text></View>{invoice.items.map((item, index) => <View style={s.row} key={index}><Text style={s.desc}>{item.description}</Text><Text style={s.col}>{item.hsnCode || "—"}</Text><Text style={s.col}>{item.quantity} {item.unit}</Text><Text style={s.col}>{money(item.rate)}</Text><Text style={s.col}>{item.gstRate}%</Text><Text style={s.col}>{money(item.quantity * item.rate * (1 + item.gstRate / 100))}</Text></View>)}</View><View style={s.totals}><View style={s.total}><Text>Taxable amount</Text><Text>{money(subtotal)}</Text></View>{(invoice.igst ?? 0) > 0 ? <View style={s.total}><Text>IGST</Text><Text>{money(invoice.igst!)}</Text></View> : <><View style={s.total}><Text>CGST</Text><Text>{money(invoice.cgst ?? tax / 2)}</Text></View><View style={s.total}><Text>SGST</Text><Text>{money(invoice.sgst ?? tax / 2)}</Text></View></>}<View style={[s.total, { borderTopWidth: 1, paddingTop: 5, fontWeight: "bold" }]}><Text>Grand total</Text><Text>{money(total)}</Text></View></View><View style={s.footer}><Text>Amount in words: {amountInWords(total)}</Text><Text>Bank: {business?.bankName || "—"} | A/C: {business?.bankAccountNumber || "—"} | IFSC: {business?.bankIfsc || "—"}</Text><Text style={{ marginTop: 25 }}>Authorised signature: ____________________</Text><Text style={{ marginTop: 8 }}>This is a computer-generated GST invoice.</Text></View></Page></Document> }
export function DownloadInvoicePDF(props: Props) { const upi = props.business?.upiId ? `upi://pay?pa=${encodeURIComponent(props.business.upiId)}&am=${props.invoice.grandTotal ?? ""}&cu=INR` : ""; return <span className="inline-flex items-center gap-2"><PDFDownloadLink document={<GSTInvoice {...props} />} fileName={`${props.invoice.number}.pdf`} className="rounded-md border px-3 py-2 text-sm font-semibold">{({ loading }) => loading ? "Preparing PDF…" : "Download PDF"}</PDFDownloadLink>{upi && <span className="hidden"><QRCodeSVG value={upi} size={64}/></span>}</span>; }
