import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireUserId } from "@/lib/api-auth";
const money = (n: number) => `₹${Math.round(n).toLocaleString("en-IN")}`;
function dates(q: string) { const now = new Date(); const start = new Date(now); if (/today|aaj/i.test(q)) start.setHours(0,0,0,0); else if (/last week|pichhle hafte/i.test(q)) { start.setDate(start.getDate()-7); now.setDate(now.getDate()-7); } else if (/this month|is mahine/i.test(q)) start.setDate(1); else return {}; return { gte: start, lte: now }; }
export async function POST(request: Request) { const auth = await requireUserId(); if ("error" in auth) return auth.error; const parsed = z.object({ query: z.string().trim().min(2).max(500) }).safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Please enter a valid question." }, { status: 400 }); const q = parsed.data.query; const hinglish = /[ािीुूेैोौ]|kitna|kitne|baki|baaki|kamai|aaj|mahine/i.test(q); const where = { userId: auth.userId, invoiceDate: dates(q) }; let intent = "general", answer = hinglish ? "Main sales, GST, pending payments aur inventory ke baare mein help kar sakta hoon." : "I can help with sales, GST, pending payments, and inventory.";
try { if (/pending|baki|baaki|unpaid/i.test(q)) { intent = "pending_amount"; const x = await prisma.invoice.aggregate({ where: { userId: auth.userId, paymentStatus: { not: "PAID" } }, _sum: { grandTotal: true }, _count: true }); answer = hinglish ? `${money(x._sum.grandTotal ?? 0)} pending hai — ${x._count} unpaid invoices.` : `${money(x._sum.grandTotal ?? 0)} is pending across ${x._count} unpaid invoices.`; }
else if (/gst|tax/i.test(q)) { intent = "gst_summary"; const x = await prisma.invoice.aggregate({ where, _sum: { cgst: true, sgst: true, igst: true } }); answer = `CGST ${money(x._sum.cgst ?? 0)}, SGST ${money(x._sum.sgst ?? 0)}, IGST ${money(x._sum.igst ?? 0)}.`; }
else if (/invoice.*(count|kitne)|kitne.*invoice/i.test(q)) { intent = "invoice_count"; const x = await prisma.invoice.count({ where }); answer = hinglish ? `${x} invoices bane hain.` : `${x} invoices were created.`; }
else if (/revenue|kamai|total/i.test(q)) { intent = "revenue"; const x = await prisma.invoice.aggregate({ where, _sum: { grandTotal: true } }); answer = hinglish ? `Total revenue ${money(x._sum.grandTotal ?? 0)} hai.` : `Total revenue is ${money(x._sum.grandTotal ?? 0)}.`; }
else if (/stock|reorder/i.test(q)) { intent = "reorder_check"; const products = await prisma.product.findMany({ where: { userId: auth.userId } }); const low = products.filter(p => p.currentStock <= p.reorderLevel); answer = low.length ? (hinglish ? `Reorder karein: ${low.map(p => `${p.name} (${p.currentStock} ${p.unit})`).join(", ")}.` : `Reorder: ${low.map(p => `${p.name} (${p.currentStock} ${p.unit})`).join(", ")}.`) : (hinglish ? "Abhi koi low-stock item nahi hai." : "No items are currently low in stock."); }
else if (/product|saman|item|bikne/i.test(q)) { intent = "top_products"; const lines = await prisma.lineItem.findMany({ where: { invoice: { userId: auth.userId } } }); const totals = new Map<string, number>(); lines.forEach(x => totals.set(x.description, (totals.get(x.description) ?? 0)+x.totalAmount)); const top = Array.from(totals.entries()).sort((a,b) => b[1]-a[1]).slice(0,3).map(([n]) => n); answer = top.length ? (hinglish ? `Top products: ${top.join(", ")}.` : `Top products: ${top.join(", ")}.`) : "No product sales yet."; }
await prisma.auditLog.create({ data: { userId: auth.userId, action: "AGENT_QUERY", metadata: { query: q, intent, answer } } }); return NextResponse.json({ answer, intent }); } catch { return NextResponse.json({ error: "Could not answer your question." }, { status: 500 }); } }
