import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireUserId } from "@/lib/api-auth";
import { badRequest, statusSchema } from "@/lib/validation";
const present = (invoice: any) => ({ id: invoice.id, number: invoice.invoiceNumber, customer: invoice.customer.name, customerId: invoice.customerId, date: invoice.invoiceDate.toISOString().slice(0, 10), dueDate: invoice.dueDate?.toISOString().slice(0, 10) ?? null, rawInput: invoice.rawInput, status: invoice.paymentStatus, subtotal: invoice.subtotal, cgst: invoice.cgst, sgst: invoice.sgst, igst: invoice.igst, totalTax: invoice.totalTax, grandTotal: invoice.grandTotal, items: invoice.lineItems.map((item: any) => ({ description: item.description, hsnCode: item.hsnCode ?? "", quantity: item.quantity, unit: item.unit, rate: item.rate, gstRate: item.gstRate })) });

const owned = (id: string, userId: string) => prisma.invoice.findFirst({ where: { id, userId }, include: { customer: true, lineItems: true } });
export async function GET(_: Request, { params }: { params: { id: string } }) { const auth = await requireUserId(); if ("error" in auth) return auth.error; const invoice = await owned(params.id, auth.userId); return invoice ? NextResponse.json(present(invoice)) : NextResponse.json({ error: "Not found" }, { status: 404 }); }
export async function PATCH(request: Request, { params }: { params: { id: string } }) { const auth = await requireUserId(); if ("error" in auth) return auth.error; const parsed = statusSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json(badRequest(parsed.error), { status: 400 }); const invoice = await prisma.invoice.updateMany({ where: { id: params.id, userId: auth.userId }, data: { paymentStatus: parsed.data.status } }); if (!invoice.count) return NextResponse.json({ error: "Not found" }, { status: 404 }); await prisma.auditLog.create({ data: { userId: auth.userId, invoiceId: params.id, action: "PAYMENT_STATUS_CHANGED", metadata: { status: parsed.data.status } } }); return NextResponse.json({ ok: true, status: parsed.data.status }); }
export async function DELETE(_: Request, { params }: { params: { id: string } }) { const auth = await requireUserId(); if ("error" in auth) return auth.error; const result = await prisma.invoice.deleteMany({ where: { id: params.id, userId: auth.userId } }); if (!result.count) return NextResponse.json({ error: "Not found" }, { status: 404 }); await prisma.auditLog.create({ data: { userId: auth.userId, invoiceId: params.id, action: "INVOICE_VOIDED" } }); return new NextResponse(null, { status: 204 }); }
