"use client";
// @ts-nocheck

import { FormEvent, useEffect, useMemo, useState } from "react";
import { signIn, useSession } from "next-auth/react";
import { DownloadInvoicePDF } from "@/components/invoice/InvoicePDF";
import { formatCurrency } from "@/lib/gst";
import { QRCodeSVG } from "qrcode.react";
import { AlertBanner } from "@/components/AlertBanner";
import { AgentQueryBar } from "@/components/AgentQueryBar";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, PieChart, Pie, Cell, BarChart, Bar, CartesianGrid } from "recharts";

type Item = { description: string; hsnCode: string; quantity: number; unit: string; rate: number; gstRate: number };
type Customer = { id: string; name: string; phone?: string | null; email?: string | null; gstin?: string | null; address?: string | null; state?: string | null };
type Invoice = { id: string; number: string; customer: string; customerId?: string; date: string; dueDate?: string | null; rawInput: string; status: "PAID" | "PENDING" | "PARTIAL" | "OVERDUE"; items: Item[]; subtotal: number; cgst: number; sgst: number; igst: number; totalTax: number; grandTotal: number };
type Profile = { businessName?: string | null; gstin?: string | null; address?: string | null; state?: string | null; phone?: string | null; logoUrl?: string | null; bankName?: string | null; bankAccountNumber?: string | null; bankIfsc?: string | null; upiId?: string | null };
type Review = { approved: boolean; interstate: boolean; issues: { field: string; severity: string; message: string }[]; totals: Omit<Invoice, "id" | "number" | "customer" | "date" | "status" | "items" | "rawInput"> };
type View = "dashboard" | "create" | "invoices" | "customers" | "inventory" | "analytics" | "settings";
const blankCustomer = { name: "", phone: "", email: "", gstin: "", address: "", state: "" };
const blankProfile: Profile = { businessName: "", gstin: "", address: "", state: "", phone: "", logoUrl: "", bankName: "", bankAccountNumber: "", bankIfsc: "", upiId: "" };
const nav: View[] = ["dashboard", "create", "invoices", "customers", "inventory", "analytics", "settings"];
const label: Record<View, string> = { dashboard: "Dashboard", create: "Create invoice", invoices: "Invoices", customers: "Customers", inventory: "Inventory", analytics: "Analytics", settings: "Business settings" };
const hindiLabel: Record<View, string> = { dashboard: "डैशबोर्ड", create: "नया बिल", invoices: "बिल", customers: "ग्राहक", inventory: "स्टॉक", analytics: "हिसाब", settings: "दुकान की जानकारी" };

function Inventory() { const [items, setItems] = useState<{ id: string; name: string; unit: string; currentStock: number; reorderLevel: number }[]>([]); const [name, setName] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const load = async () => { const r = await fetch("/api/products"); const data = await r.json(); if (r.ok) setItems(data); else setMessage(data.error || "Could not load inventory."); }; useEffect(() => { void load(); }, []); const add = async () => { if (!name.trim()) return setMessage("Enter a product name first."); setSaving(true); setMessage("Adding product…"); try { const r = await fetch("/api/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim(), unit: "pcs", currentStock: 0, reorderLevel: 10 }) }); const data = await r.json(); if (!r.ok) return setMessage(data.error || "Could not add product."); setName(""); setMessage(`${data.name} added successfully.`); await load(); } catch { setMessage("Network error. Please try again."); } finally { setSaving(false); } }; const restock = async (id: string) => { const quantity = Number(window.prompt("Quantity to add", "1")); if (!quantity || quantity < 0) return; setMessage("Updating stock…"); const r = await fetch("/api/products/restock", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ productId: id, quantity }) }); const data = await r.json(); setMessage(r.ok ? "Stock updated successfully." : data.error || "Could not update stock."); if (r.ok) await load(); }; return <section className="rounded-xl border bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-bold">Inventory</h2><div><input className="rounded border p-2" value={name} onChange={e => setName(e.target.value)} placeholder="Product name" /><button disabled={saving} onClick={add} className="ml-2 rounded bg-forest px-3 py-2 text-white disabled:opacity-60">{saving ? "Adding…" : "Add product"}</button></div></div>{message && <p className={`mt-3 text-sm ${message.includes("success") || message.includes("Adding") || message.includes("Updating") ? "text-emerald-700" : "text-red-600"}`}>{message}</p>}<table className="mt-4 w-full text-sm"><thead><tr><th>Product</th><th>Stock</th><th>Level</th><th>Status</th><th /></tr></thead><tbody>{items.map(p => <tr className="border-t" key={p.id}><td className="p-3">{p.name}</td><td>{p.currentStock} {p.unit}</td><td>{p.reorderLevel}</td><td>{p.currentStock <= p.reorderLevel ? "⚠️ Low" : "✅ OK"}</td><td><button onClick={() => restock(p.id)} className="rounded border px-2 py-1">Restock</button></td></tr>)}{!items.length && <tr><td colSpan={5} className="p-5 text-center text-gray-500">No products yet.</td></tr>}</tbody></table></section>; }

export default function Dashboard() {
  const { status } = useSession(); const [view, setView] = useState<View>("dashboard"); const [invoices, setInvoices] = useState<Invoice[]>([]); const [profile, setProfile] = useState<Profile>(blankProfile); const [selected, setSelected] = useState<Invoice | null>(null); const [language, setLanguage] = useState<"en" | "hi">("en");
  const load = async () => { const [i, p] = await Promise.all([fetch("/api/invoices"), fetch("/api/settings")]); if (i.ok) setInvoices(await i.json()); if (p.ok) setProfile(await p.json()); };
  useEffect(() => { if (status === "authenticated") void load(); }, [status]);
  useEffect(() => { const saved = window.localStorage.getItem("hisaabkaro-language"); if (saved === "hi") setLanguage("hi"); }, []);
  const toggleLanguage = () => setLanguage(current => { const next = current === "en" ? "hi" : "en"; window.localStorage.setItem("hisaabkaro-language", next); return next; });
  if (status === "loading") return <main className="grid min-h-screen place-items-center">Loading…</main>;
  if (status !== "authenticated") return <main className="grid min-h-screen place-items-center bg-canvas p-6 text-center"><div><h1 className="text-3xl font-bold text-forest">HisaabKaro</h1><p className="mt-2 text-gray-600">Private GST billing for your business.</p><button onClick={() => signIn("google", { callbackUrl: "/dashboard" })} className="mt-5 rounded bg-forest px-5 py-3 font-semibold text-white">Continue with Google</button></div></main>;
  const navText = language === "hi" ? hindiLabel : label;
  return <main className="min-h-screen bg-canvas lg:flex"><aside className="border-b bg-forest text-white lg:sticky lg:top-0 lg:min-h-screen lg:w-64 lg:border-b-0"><div className="flex items-center justify-between px-5 py-5"><b className="text-xl">Hisaab<span className="text-amber">Karo</span></b><button onClick={toggleLanguage} className="rounded border border-white/40 px-2 py-1 text-xs font-semibold">{language === "en" ? "हिंदी" : "English"}</button></div><p className="px-5 pb-3 text-xs text-white/60">{language === "hi" ? "अपना हिसाब, अपनी भाषा में" : "Simple billing for your shop"}</p><nav className="flex overflow-x-auto px-3 pb-3 lg:block lg:space-y-1">{nav.map(x => <button key={x} onClick={() => { setSelected(null); setView(x); }} className={`whitespace-nowrap rounded px-3 py-2.5 text-left text-sm lg:block lg:w-full ${view === x ? "bg-white text-forest" : "text-white/80 hover:bg-white/10"}`}>{navText[x]}</button>)}</nav></aside><div className="min-w-0 flex-1"><div className="mx-auto max-w-7xl p-5 pb-24 sm:p-8"><AlertBanner /><h1 className="mb-5 text-2xl font-bold">{navText[view]}</h1>{selected ? <InvoiceDetail invoice={selected} profile={profile} onClose={() => setSelected(null)} /> : view === "dashboard" ? <Overview invoices={invoices} go={setView} /> : view === "create" ? <Creator profile={profile} onCreated={x => { setInvoices(a => [x, ...a]); setSelected(x); setView("invoices"); }} /> : view === "invoices" ? <InvoiceList invoices={invoices} onSelect={setSelected} /> : view === "customers" ? <Customers /> : view === "inventory" ? <Inventory /> : view === "analytics" ? <Analytics /> : <Settings profile={profile} onSaved={setProfile} />}</div></div><AgentQueryBar /></main>;
}
function Overview({ invoices, go }: { invoices: Invoice[]; go: (x: View) => void }) { const revenue = invoices.reduce((a, i) => a + i.grandTotal, 0), pending = invoices.filter(i => i.status !== "PAID").reduce((a, i) => a + i.grandTotal, 0); return <><div className="grid gap-4 sm:grid-cols-3"><Card title="Revenue" value={formatCurrency(revenue)} /><Card title="Invoices" value={String(invoices.length)} /><Card title="Pending payments" value={formatCurrency(pending)} /></div><section className="mt-6 rounded-xl border bg-white p-5"><h2 className="font-bold">Ready to record a sale?</h2><p className="mt-1 text-sm text-gray-600">Describe it in English, Hindi, or Hinglish. Review GST before saving.</p><button onClick={() => go("create")} className="mt-4 rounded bg-forest px-4 py-2 text-white">Create with AI</button></section></> }
function Card({ title, value }: { title: string; value: string }) { return <div className="rounded-xl border bg-white p-5"><p className="text-sm text-gray-500">{title}</p><p className="mt-2 text-2xl font-bold">{value}</p></div> }
function Creator({ profile, onCreated }: { profile: Profile; onCreated: (x: Invoice) => void }) {
  const [input, setInput] = useState("राम जी को 10 किलो आटा ₹45 प्रति किलो बेचा"); const [customer, setCustomer] = useState(""); const [customerId, setCustomerId] = useState(""); const [customers, setCustomers] = useState<Customer[]>([]); const [items, setItems] = useState<Item[]>([]); const [review, setReview] = useState<Review | null>(null); const [message, setMessage] = useState(""); const [dueDate, setDueDate] = useState("");
  useEffect(() => { fetch("/api/customers").then(r => r.ok ? r.json() : []).then((saved: Customer[]) => { setCustomers(saved); if (saved[0]) { setCustomerId(saved[0].id); setCustomer(saved[0].name); } }); }, []);
  const parse = async () => { setMessage("Parsing sale…"); const r = await fetch("/api/agent/parse", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ input }) }); const x = await r.json(); if (!r.ok) return setMessage(x.error); setCustomer(x.customerName); setItems(x.items); setMessage(x.clarification || "Edit details, choose a saved customer, then review compliance."); };
  const choose = (id: string) => { setCustomerId(id); if (id === "walk-in") { setCustomer("Walk-in customer"); return; } const c = customers.find(x => x.id === id); if (c) setCustomer(c.name); };
  const runReview = async () => { const c = customers.find(x => x.id === customerId); const payload = { seller: profile, customer: c ?? { name: customer || "Walk-in customer", state: profile.state }, items, invoiceDate: new Date().toISOString().slice(0, 10), dueDate: dueDate || null }; const r = await fetch("/api/agent/review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const x = await r.json(); setReview(r.ok ? x : null); setMessage(r.ok ? "" : x.error); };
  const save = async () => { if (!review?.approved) return setMessage("Resolve compliance errors and review again before saving."); const r = await fetch("/api/invoices", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customerId: customerId || undefined, customer, rawInput: input, date: new Date().toISOString().slice(0, 10), dueDate: dueDate || null, items }) }); const x = await r.json(); if (!r.ok) { setMessage(x.error || "Could not save invoice."); if (x.review) setReview(x.review); return; } onCreated(x); };
  const edit = (i: number, key: keyof Item, value: string) => { setItems(old => old.map((x, n) => n === i ? { ...x, [key]: ["quantity", "rate", "gstRate"].includes(key) ? Number(value) : value } : x)); setReview(null); };
  return <div className="space-y-5"><section className="rounded-xl border bg-white p-5"><label className="font-semibold">Describe your sale</label><textarea className="mt-2 min-h-28 w-full rounded border p-3" value={input} onChange={e => setInput(e.target.value)} /><p className="mt-2 text-xs text-gray-500">Try: शर्मा जी को 5 साबुन और 2 लीटर तेल बेचा</p><button onClick={parse} className="mt-3 rounded bg-amber px-4 py-2 font-semibold">Parse with AI</button></section>{items.length > 0 && <section className="rounded-xl border bg-white p-5"><label className="block text-sm font-semibold">Saved customer <span className="font-normal text-gray-500">(your first saved customer is selected by default)</span><select className="mt-1 block w-full rounded border p-2" value={customerId} onChange={e => choose(e.target.value)}><option value="">Choose customer</option>{customers.map(c => <option value={c.id} key={c.id}>{c.name} — {c.state || "no state"}</option>)}</select></label>{!customers.length && <p className="mt-2 text-sm text-amber-700">Add a customer first in the Customers tab, including GSTIN and state.</p>}<label className="mt-3 block text-sm font-semibold">Due date<input type="date" value={dueDate} onChange={e => { setDueDate(e.target.value); setReview(null); }} className="mt-1 block rounded border p-2" /></label><div className="mt-5 overflow-auto"><table className="min-w-[700px] w-full text-sm"><thead><tr className="border-b text-left"><th>Item</th><th>HSN</th><th>Qty</th><th>Unit</th><th>Rate</th><th>GST</th></tr></thead><tbody>{items.map((x, i) => <tr key={i} className="border-b">{(["description", "hsnCode", "quantity", "unit", "rate", "gstRate"] as (keyof Item)[]).map(k => <td className="p-2" key={k}><input value={x[k]} onChange={e => edit(i, k, e.target.value)} className="w-24 rounded border p-1" /></td>)}</tr>)}</tbody></table></div><button onClick={runReview} className="mt-4 rounded border border-forest px-4 py-2 text-forest">Review again</button><ReviewBox review={review} seller={profile.state} customer={customers.find(x => x.id === customerId)?.state} /><button onClick={save} disabled={!review?.approved} className="mt-4 rounded bg-forest px-4 py-2 text-white disabled:opacity-40">Confirm & generate invoice</button></section>}<p className="text-sm text-red-600">{message}</p></div>;
}
function ReviewBox({ review, seller, customer }: { review: Review | null; seller?: string | null; customer?: string | null }) { if (!review) return <div className="mt-5 rounded border border-amber bg-amber/10 p-3 text-sm">Compliance review pending. Tax mode will use seller state ({seller || "missing"}) and customer state ({customer || "missing"}).</div>; return <div className={`mt-5 rounded border p-3 text-sm ${review.approved ? "border-emerald-300 bg-emerald-50" : "border-red-300 bg-red-50"}`}><b>{review.approved ? "Compliance approved" : "Needs correction"}</b><p className="mt-1">{review.interstate ? "Outside state: IGST" : "Within state: CGST + SGST"}</p>{review.issues.map((x, i) => <p className="mt-1" key={i}>{x.field}: {x.message}</p>)}</div> }
function InvoiceList({ invoices, onSelect }: { invoices: Invoice[]; onSelect: (x: Invoice) => void }) { return <section className="overflow-auto rounded-xl border bg-white"><table className="min-w-[650px] w-full text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-3">Number</th><th>Customer</th><th>Date</th><th>Status</th><th>Total</th></tr></thead><tbody>{invoices.map(x => <tr className="cursor-pointer border-t hover:bg-gray-50" key={x.id} onClick={() => onSelect(x)}><td className="p-3 font-semibold">{x.number}</td><td>{x.customer}</td><td>{x.date}</td><td>{x.status}</td><td>{formatCurrency(x.grandTotal)}</td></tr>)}{!invoices.length && <tr><td className="p-5 text-gray-500" colSpan={5}>No invoices yet.</td></tr>}</tbody></table></section> }
function Customers() { const [items, setItems] = useState<Customer[]>([]); const [form, setForm] = useState(blankCustomer); const [editing, setEditing] = useState<string | null>(null); const [error, setError] = useState(""); const load = async () => { const response = await fetch("/api/customers"); setItems(await response.json()); }; useEffect(() => { void load(); }, []); const submit = async (e: FormEvent) => { e.preventDefault(); const r = await fetch(editing ? `/api/customers/${editing}` : "/api/customers", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const x = await r.json(); if (!r.ok) return setError(Object.values(x.fields || {}).flat().join(" ") || x.error); setForm(blankCustomer); setEditing(null); setError(""); void load(); }; return <div className="grid gap-5 lg:grid-cols-2"><form onSubmit={submit} className="rounded-xl border bg-white p-5"><h2 className="font-bold">{editing ? "Edit customer" : "Add customer"}</h2>{Object.keys(blankCustomer).map(k => <label className="mt-3 block text-sm capitalize" key={k}>{k}<input value={form[k as keyof typeof form]} onChange={e => setForm({ ...form, [k]: e.target.value })} className="mt-1 block w-full rounded border p-2" /></label>)}<p className="mt-2 text-sm text-red-600">{error}</p><button className="mt-4 rounded bg-forest px-4 py-2 text-white">Save customer</button></form><div className="rounded-xl border bg-white p-5"><h2 className="font-bold">Saved customers</h2>{items.map(c => <button className="mt-3 block w-full rounded border p-3 text-left hover:bg-gray-50" key={c.id} onClick={() => { setEditing(c.id); setForm({ name: c.name, phone: c.phone || "", email: c.email || "", gstin: c.gstin || "", address: c.address || "", state: c.state || "" }); }}><b>{c.name}</b><br /><span className="text-sm text-gray-500">{c.state || "No state"} · {c.gstin || "No GSTIN"}</span></button>)}</div></div> }
function Settings({ profile, onSaved }: { profile: Profile; onSaved: (x: Profile) => void }) { const [form, setForm] = useState(profile); const [message, setMessage] = useState(""); useEffect(() => setForm(profile), [profile]); const submit = async (e: FormEvent) => { e.preventDefault(); const r = await fetch("/api/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const x = await r.json(); if (!r.ok) return setMessage(Object.values(x.fields || {}).flat().join(" ") || x.error); onSaved(x); setMessage("Saved successfully."); }; return <form onSubmit={submit} className="max-w-2xl rounded-xl border bg-white p-5"><p className="mb-3 text-sm text-gray-600">These business details appear on compliance checks and every PDF.</p>{Object.keys(blankProfile).map(k => <label className="mt-3 block text-sm capitalize" key={k}>{k.replace(/([A-Z])/g, " $1")}<input value={form[k as keyof Profile] || ""} onChange={e => setForm({ ...form, [k]: e.target.value })} className="mt-1 block w-full rounded border p-2" /></label>)}<p className="mt-3 text-sm">{message}</p><button className="mt-4 rounded bg-forest px-4 py-2 text-white">Save business profile</button></form> }
function Analytics() { const [range, setRange] = useState("month"); const [data, setData] = useState<any>(null); const dates = useMemo(() => { const now = new Date(), from = new Date(now); if (range === "today") from.setHours(0,0,0,0); else if (range === "month") from.setDate(1); else { from.setMonth(3, 1); if (now.getMonth() < 3) from.setFullYear(now.getFullYear() - 1); } return { from: from.toISOString().slice(0, 10), to: now.toISOString().slice(0, 10) }; }, [range]); useEffect(() => { fetch(`/api/analytics?from=${dates.from}&to=${dates.to}`).then(r => r.json()).then(setData); }, [dates]); if (!data) return <p>Loading analytics…</p>; return <section className="space-y-5"><div className="flex gap-2"><select value={range} onChange={e => setRange(e.target.value)} className="rounded border p-2"><option value="today">Today</option><option value="month">This month</option><option value="fy">This financial year</option></select><a className="rounded border border-forest px-3 py-2 text-forest" href={`/api/gst-export?from=${dates.from}&to=${dates.to}`}>Download GSTR-1 CSV</a></div><div className="grid gap-3 sm:grid-cols-3"><Card title="Revenue" value={formatCurrency(data.revenue)} /><Card title="Taxable amount" value={formatCurrency(data.subtotal)} /><Card title="Average invoice" value={formatCurrency(data.averageInvoice)} /><Card title="CGST" value={formatCurrency(data.cgst)} /><Card title="SGST" value={formatCurrency(data.sgst)} /><Card title="IGST" value={formatCurrency(data.igst)} /><Card title="Invoice count" value={String(data.count)} /></div><section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Products by sales</h2>{Object.entries(data.categories).map(([name, amount]) => <div key={name} className="mt-3 flex justify-between border-b pb-2"><span>{name}</span><b>{formatCurrency(amount as number)}</b></div>)}</section></section> }
function InvoiceDetail({ invoice, profile, onClose }: { invoice: Invoice; profile: Profile; onClose: () => void }) {
  const upi = profile.upiId ? `upi://pay?pa=${encodeURIComponent(profile.upiId)}&pn=${encodeURIComponent(profile.businessName || "HisaabKaro")}&am=${invoice.grandTotal}&cu=INR&tn=${encodeURIComponent(invoice.number)}` : "";
  const reminder = `https://wa.me/?text=${encodeURIComponent(`Namaste ${invoice.customer}, payment of ${formatCurrency(invoice.grandTotal)} for invoice ${invoice.number}${invoice.dueDate ? ` is due on ${invoice.dueDate}` : " is pending"}. ${upi ? `Pay securely via UPI: ${upi}` : ""}`)}`;
  return <section className="rounded-xl border bg-white p-5"><button onClick={onClose} className="text-sm text-forest">Back to invoices</button><h2 className="mt-3 text-xl font-bold">{invoice.number}</h2><p>{invoice.customer} · {invoice.date} · {invoice.igst ? "Outside state: IGST" : "Within state: CGST + SGST"}</p><p className="mt-3 text-2xl font-bold">{formatCurrency(invoice.grandTotal)}</p><div className="mt-5 flex flex-wrap gap-3"><DownloadInvoicePDF invoice={invoice} business={profile} /><a href={reminder} target="_blank" className="rounded border px-3 py-2 text-sm font-semibold">{invoice.status === "PAID" ? "Share invoice" : "Send payment reminder"}</a></div>{upi && <PaymentQR value={upi} />}</section>
}
function PaymentQR({ value }: { value: string }) { return <div className="mt-5 inline-flex items-center gap-3 rounded-lg border border-emerald-200 bg-emerald-50 p-3"><QRCodeSVG value={value} size={96} /><p className="text-sm"><b>Scan to pay by UPI</b><br />Open any UPI app and scan this code.</p></div>; }
